# Generated by Django 5.2.1 on 2025-06-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_flavours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flavours',
            new_name='Flavour',
        ),
    ]
